apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: securebank-secrets
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: securebank
            - name: MYSQL_USER
              value: bankuser
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: securebank-secrets
                  key: mysql-password
          volumeMounts:
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 20
            periodSeconds: 5
      volumes:
        - name: mysql-init
          configMap:
            name: mysql-init-sql